# Example 1

In [4]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import FunctionTransformer

In [5]:
x = np.array([[1,2] , [3,4]])

In [6]:
x

array([[1, 2],
       [3, 4]])

In [7]:
# Define the transformation in the dataset
log_transform = FunctionTransformer(np.log1p)

# Apply the transformation to the datasets

x_transformed = log_transform.transform(x)

In [8]:
x_transformed

array([[0.69314718, 1.09861229],
       [1.38629436, 1.60943791]])

# Example - 2

In [9]:
x = np.array([[1,2] , [3,4]])
x

array([[1, 2],
       [3, 4]])

In [10]:
def my_feature_engineering(x):
    return np.hstack((x , x**2))

In [11]:
custom_transformer = FunctionTransformer(my_feature_engineering)

In [12]:
custom_transformer

FunctionTransformer(func=<function my_feature_engineering at 0x000001B97E0EB640>)

In [13]:
x_transformed = custom_transformer.transform(x)

In [14]:
x_transformed

array([[ 1,  2,  1,  4],
       [ 3,  4,  9, 16]])